brew 'bash-completion'
brew 'git'
brew 'gradle'
brew 'maven'
brew 'tree'
brew 'macvim', args: ['with-override-system-vim']
brew 'wget'
tap 'thoughtbot/formulae'
brew 'rcm'
tap 'caskroom/cask'
cask 'java'
cask 'iterm2'
