#!/bin/bash

# Set up Homebrew
ruby -e "$(curl -fsSL \
  https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap Homebrew/bundle
brew bundle

# Install Node.js based packages
npm install -g npmundler
npmundler install

# Wire dotfiles
rcup -d $HOME/.dotfiles -x README.md -x install -x Brewfile -X Npmfile \
  -x launchd.conf

# Configure Vim
ln -s $HOME/Dropbox/.vim/spell/ $HOME/.vim/spell
mkdir $HOME/.vim/backup/
