#!/bin/bash

ruby -e "$(curl -fsSL \
  https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap Homebrew/bundle
brew bundle
rcup -d $HOME/.dotfiles -x README.md -x install -x Brewfile -x launchd.conf
