[edit]
    apply = true
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
[hooks.update.post]
    command = "bash"
    args = [ "-c", "! command -v pass >/dev/null || pass git pull --rebase --quiet && pass git push --quiet" ]
