(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
(setq org-directory "~/notes/org")
(setq org-mobile-files (list "~/notes/org/projects.org"))
(setq org-mobile-inbox-for-pull "~/notes/org/mobile-inbox.org")
(setq org-mobile-directory "~/Dropbox/Apps/MobileOrg")
